<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE module [
  <!ELEMENT module (dtdversion,name,version,description*,help*,about*,requires*,file+)>
  <!ELEMENT dtdversion (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT version (#PCDATA)>
  <!ELEMENT mincmsversion (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT help (#PCDATA)>
  <!ELEMENT about (#PCDATA)>
  <!ELEMENT requires (requiredname,requiredversion)>
  <!ELEMENT requiredname (#PCDATA)>
  <!ELEMENT requiredversion (#PCDATA)>
  <!ELEMENT file (filename,isdir,data)>
  <!ELEMENT filename (#PCDATA)>
  <!ELEMENT isdir (#PCDATA)>
  <!ELEMENT data (#PCDATA)>
]>
<module>
	<dtdversion>1.3</dtdversion>
	<name>Xinha</name>
	<version>0.2.0</version>
  <mincmsversion>1.2.1</mincmsversion>
	<help>PGgzPldoYXQgZG9lcyB0aGlzIGRvPzwvaDM+DQogICAgPHA+RW5hYmxlcyA8Yj5YaW5oYTwvYj4gdG8gYmUgdXNlZCBhcyBhIFdZU0lXWUcuPC9wPg0KICAgIDxoMz5Ib3cgZG8gSSB1c2UgaXQ/PC9oMz4NCiAgICA8cD5JbnN0YWxsIGl0LCB0aGVuIGdvIHRvIFVzZXIgUHJlZmVyZW5jZXMgYW5kIFNldCA8Yj5YaW5oYTwvYj4gdG8gYmUgeW91ciB3eXNpd3lnIG9mIGNob2ljZS48L3A+JiMwMzk7Ow0KICAgIDxwPlRvIGN1c3RvbWl6ZSBpdCB0aGUgcGVybWlzc2lvbiA8aT5Nb2RpZnkgWGluaGEtc2V0dGluZ3M8L2k+IG11c3QgYmUgc2V0IGZvciB5b3UgZ3JvdXAuPC9wPjxoMz5QYXJhbWV0cmU8L2gzPjx1bD48bGk+PGVtPihvcHRpb25hbCk8L2VtPiBsYW5nPSJlbl9VUyIgLSBQYXJhbWV0cmV0IGFuZ2l2ZXIgaHZpbGVyIHNwcm9nIGRlciBza2FsIGJydWdlcyB0aWwgdmlzbmluZyBmb3IgYmVzJm9zbGFzaDtnZW5kZS4gSWtrZSBhbGxlIG1vZHVsZXIgdW5kZXJzdCZvc2xhc2g7dHRlciBlbGxlciBiZWgmb3NsYXNoO3ZlciBkZXR0ZS48L2xpPjwvdWw+</help>
	<about>PGJyIC8+TGF2ZXQgYWY6IE1vcnRlbiBQb3Vsc2VuICZsdDsmbHQ7bW9ydGVuQHBvdWxzZW4ub3JnJmd0OyZndDs8YnIgLz48YnIgLz5WZXJzaW9uOiAwLjIuMDxiciAvPjxiciAvPkhpc3RvcmlrIG92ZXIgJmFlbGlnO25kcmluZ2VyOjxiciAvPgkJPHVsPg0KCQk8bGk+DQoJCTxwPlZlcnNpb246IDAuMS4zPC9wPg0KCQk8cD5QcmVwYXJlZCBpdCB0byBiZSBvcHRpb25hbCB3aGV0aGVyIHRoZSBjbXNtc2xpbmtlciBzaG91bGQgZ2VuZXJhdGUgaHJlZi1zdHlsZSBvciB7Y21zLXNlbGZsaW5rfS1zdHlsZSBsaW5rczwvcD4NCgkJPC9saT4NCgkJPGxpPg0KCQk8cD5WZXJzaW9uOiAwLjEuMjwvcD4NCgkJPHA+QWRkZWQgcGVybWlzc2lvbiB0byBjaGFuZ2Ugc2V0dGluZ3M8L3A+DQoJCTxwPkFkZGVkIGEgQ01TLWxpbmtlciBtb2R1bGUgdG8gWGluaGE8L3A+DQoJCTxwPkFkZGVkIHRoZSBNdWx0aUNvbmZpZ3VyYXRpb24gcGx1Z2luIHRvIFhpbmhhPC9wPg0KCQk8L2xpPg0KCQk8bGk+DQoJCTxwPlZlcnNpb246IDAuMS4xPC9wPg0KCQk8cD5GaXhlZCBhdXRvZGV0ZWN0aW9uIG9mIFN3ZWRpc2g8L3A+DQoJCTxwPkZpeGVkIHRoZSBwcm9ibGVtIHdpdGggaGFuZ2luZyBmb3JtLWJ1dHRvbnMgd2hlbiBpbiBmdWxsc2NyZWVuIG1vZGU8L3A+DQoJCTxwPk5vIHVnbHkgaGVhZGVyIHN0dWZmIGluc2VydGVkIGludG8gcGFnZXMgbm90IGNvbnRhaW5pbmcgYSAmIzAzOTt0ZXh0YXJlYSYjMDM5OyB0YWc8L3A+DQoJCTxwPkZpeGVkIFhpbmhhIG5vdCBzaG93aW5nIHdoZW4gZWRpdGluZyBuZXdzLi4uPC9wPg0KCQk8cD5BZGRlZCB3aWR0aCBvZiBlZGl0b3ItYXJlYSBhcyBhbiBvcHRpb248L3A+DQoJCTxwPkFkZGVkIGEgZXhhbXBsZSB0ZXh0LWFyZWE8L3A+DQoJCTxwPkFkZGVkIHdpZHRoIG9mIHRoZSBTdHlsaXN0IHBhbmVsIGFzIGFuIG9wdGlvbjwvcD4NCiAgICA8cD5GaXhlZCBzaG9ydF9vcGVuX3RhZ3M8L3A+DQogICAgPHA+PC9wPg0KCQk8L2xpPg0KCQk8bGk+DQoJCTxwPlZlcnNpb246IDAuMS4wPC9wPg0KCQk8cD5GaXJzdCB2ZXJzaW9uIHJlbGVhc2VkIG91dHNpZGUgc3ZuPC9wPg0KCQk8cD5GaXhlZCByZWxhdGl2ZSBpbWFnZS1zb3VyY2VzPC9wPg0KCQk8cD5Ob3cgc2hvd3MgdGhlIHN0eWxlc2hlZXQgb2YgdGhlIHBhZ2UgaWYgdGhlIHBsdWdpbiBTdHlsaXN0IGlzIGVuYWJsZWQgKGl0IGlzIGJ5IGRlZmF1bHQpPC9wPg0KCQk8L2xpPg0KCQk8bGk+DQoJCTxwPlZlcnNpb246IDAuMC4yPC9wPg0KCQk8cD5GaXhlZCBhIHByb2JsZW0gd2hpY2ggYWZmZWN0ZWQgdGhlIHRhYnMgb24gYWxsIGFkbWluLXBhZ2VzPC9wPg0KCQk8cD5GaXhlZCBzb21lIHBocDUtcmVsYXRlZCBwcm9ibGVtczwvcD4NCgkJPHA+VGhlIG1vZHVsZSBub3cgdHJpZXMgdG8gZmlndXJlIG91dCB5b3VyIGxhbmd1YWdlIHByZWZlcmVuY2UgYW5kIGFkanVzdCB0byB0aGF0PC9wPg0KCQk8L2xpPg0KCQk8bGk+DQoJCTxwPlZlcnNpb246IDAuMC4xPC9wPg0KCQk8cD5Jbml0aWFsIHRlc3QgcmVsZWFzZS48L3A+DQoJCTwvbGk+DQoJCTwvdWw+PGJyIC8+</about>
	<file>
	  <filename>/</filename>
	  <isdir>1</isdir>
	</file>
	<file>
	  <filename>/action.defaultadmin.php</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[PD9waHAKaWYgKCFpc3NldCgkZ0NtcykgfHwgISR0aGlzLT5WaXNpYmxlVG9BZG1pblVzZXIoKSkgZXhpdDsKCi8vUmVhZCBiYWNrIHRoZSBzYXZlZCB2YWx1ZXMKJHNraW4gPSAkdGhpcy0+R2V0UHJlZmVyZW5jZSgiWGluaGEuU2tpbiIpOwokd2lkdGggPSAkdGhpcy0+R2V0UHJlZmVyZW5jZSgiWGluaGEuV2lkdGgiKTsKJHdpZHRoYXV0byA9ICR0aGlzLT5HZXRQcmVmZXJlbmNlKCJYaW5oYS5XaWR0aEF1dG8iKTsKJHdpZHRodW5pdCA9ICR0aGlzLT5HZXRQcmVmZXJlbmNlKCJYaW5oYS5XaWR0aFVuaXQiKTsKJGhlaWdodCA9ICR0aGlzLT5HZXRQcmVmZXJlbmNlKCJYaW5oYS5IZWlnaHQiLCI0MDAiKTsKJGhlaWdodGF1dG8gPSAkdGhpcy0+R2V0UHJlZmVyZW5jZSgiWGluaGEuSGVpZ2h0QXV0byIsIjEiKTsKJHN0eWxpc3R3aWR0aCA9ICR0aGlzLT5HZXRQcmVmZXJlbmNlKCJYaW5oYS5TdHlsaXN0V2lkdGgiLCIyMDAiKTsKJHBsdWdpbnMgPSAkdGhpcy0+R2V0UHJlZmVyZW5jZSgiWGluaGEuUGx1Z2lucyIpOwokYm9keWNzcyA9ICR0aGlzLT5HZXRQcmVmZXJlbmNlKCJYaW5oYS5Cb2R5Q1NTIiwndGV4dC1hbGlnbjpsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiNmZmZmZmYnKTsKJGxpbmtlcmZsYXZvciA9ICR0aGlzLT5HZXRQcmVmZXJlbmNlKCJYaW5oYS5MaW5rZXJGbGF2b3IiLCJocmVmIik7CgokYWJzb2x1dGV1cmxzID0gJHRoaXMtPkdldFByZWZlcmVuY2UoIlhpbmhhLkFic29sdXRlVXJscyIsIjAiKTsKJHJlcGxhY2Vyb290dXJscyA9ICR0aGlzLT5HZXRQcmVmZXJlbmNlKCJYaW5oYS5SZXBsYWNlUm9vdFVybHMiLCIwIik7CgoKCi8vU2NhbiBmb3IgYXZhaWxhYmxlIHBsdWdpbnMKJHBsdWdpbnNfYXZhaWxhYmxlID0gQXJyYXkoKTsKJGQgPSBkaXIoZGlybmFtZShfX0ZJTEVfXykuJy94aW5oYS9wbHVnaW5zJyk7CndoaWxlICgkZW50cnkgPSAkZC0+cmVhZCgpKSB7CglpZiAoJGVudHJ5WzBdIT0nLicpIHsKCQkkcGx1Z2luc19hdmFpbGFibGVbXT10cmltKCRlbnRyeSk7Cgl9Cn0KJGQtPmNsb3NlKCk7CgovL1NjYW4gZm9yIGF2YWlsYWJsZSBza2lucwokc2tpbnNfYXZhaWxhYmxlID0gQXJyYXkoKTsKJGQgPSBkaXIoZGlybmFtZShfX0ZJTEVfXykuJy94aW5oYS9za2lucycpOwp3aGlsZSAoJGVudHJ5ID0gJGQtPnJlYWQoKSkgewoJaWYgKCRlbnRyeVswXSE9Jy4nKXsKCQkkc2tpbnNfYXZhaWxhYmxlPWFycmF5X21lcmdlKCRza2luc19hdmFpbGFibGUsYXJyYXkodHJpbSgkZW50cnkpPT50cmltKCRlbnRyeSkpKTsKCX0KfQokZC0+Y2xvc2UoKTsKJHdpZHRodW5pdHM9YXJyYXkoIiUiPT4iJSIsCSR0aGlzLT5MYW5nKCJwaXhlbHMiKT0+InB4Iik7CgokdGFiPSJzZXR0aW5ncyI7CmlmIChpc3NldCgkcGFyYW1zWyJ0YWIiXSkpICR0YWI9JHBhcmFtc1sidGFiIl07CgplY2hvICR0aGlzLT5TdGFydFRhYkhlYWRlcnMoKTsKZWNobyAkdGhpcy0+U2V0VGFiSGVhZGVyKCJzZXR0aW5ncyIsJHRoaXMtPkxhbmcoInNldHRpbmdzIiksKCR0YWI9PSJzZXR0aW5ncyIpKTsKZWNobyAkdGhpcy0+U2V0VGFiSGVhZGVyKCJwbHVnaW5zIiwkdGhpcy0+TGFuZygicGx1Z2lucyIpLCgkdGFiPT0icGx1Z2lucyIpKTsKZWNobyAkdGhpcy0+RW5kVGFiSGVhZGVycygpOwplY2hvICR0aGlzLT5TdGFydFRhYkNvbnRlbnQoKTsKZWNobyAkdGhpcy0+U3RhcnRUYWIoInNldHRpbmdzIik7CmVjaG8gIjxpbWcgc3JjPScuLi9tb2R1bGVzL1hpbmhhL3hpbmhhLXJlZC5naWYnIC8+IjsKCiR0aGlzLT5zbWFydHktPmFzc2lnbigic3RhcnRmb3JtIiwkdGhpcy0+Q3JlYXRlRm9ybVN0YXJ0KCRpZCwic2F2ZXNldHRpbmdzIiwkcmV0dXJuaWQpKTsKJHRoaXMtPnNtYXJ0eS0+YXNzaWduKCJlbmRmb3JtIiwkdGhpcy0+Q3JlYXRlRm9ybUVuZCgpKTsKCiR0aGlzLT5zbWFydHktPmFzc2lnbigic2tpbnRleHQiLCR0aGlzLT5MYW5nKCJza2luIikpOwokdGhpcy0+c21hcnR5LT5hc3NpZ24oInNraW5pbnB1dCIsJHRoaXMtPkNyZWF0ZUlucHV0RHJvcGRvd24oJGlkLCJza2luIiwkc2tpbnNfYXZhaWxhYmxlLCIiLCRza2luKSk7CgoKJHRoaXMtPnNtYXJ0eS0+YXNzaWduKCJ3aWR0aHRleHQiLCR0aGlzLT5MYW5nKCJzZWxlY3R3aWR0aCIpKTsKJHRoaXMtPnNtYXJ0eS0+YXNzaWduKCJ3aWR0aGlucHV0IiwKJHRoaXMtPkNyZWF0ZUlucHV0Q2hlY2tib3goJGlkLCJ3aWR0aGF1dG8iLCcxJywkd2lkdGhhdXRvKS4KJHRoaXMtPkxhbmcoImF1dG8iKS4KJHRoaXMtPkNyZWF0ZUlucHV0VGV4dCgkaWQsIndpZHRoIiwkd2lkdGgsJzgnLCc2JykuCiR0aGlzLT5DcmVhdGVJbnB1dERyb3Bkb3duKCRpZCwid2lkdGh1bml0Iiwkd2lkdGh1bml0cywtMSwkd2lkdGh1bml0KSk7CgokdGhpcy0+c21hcnR5LT5hc3NpZ24oImhlaWdodHRleHQiLCR0aGlzLT5MYW5nKCJzZWxlY3RoZWlnaHQiKSk7CiR0aGlzLT5zbWFydHktPmFzc2lnbigiaGVpZ2h0aW5wdXQiLAokdGhpcy0+Q3JlYXRlSW5wdXRDaGVja2JveCgkaWQsImhlaWdodGF1dG8iLCcxJywkaGVpZ2h0YXV0bykuCiR0aGlzLT5MYW5nKCJhdXRvIikuCiR0aGlzLT5DcmVhdGVJbnB1dFRleHQoJGlkLCJoZWlnaHQiLCRoZWlnaHQsJzgnLCc2JykuCiR0aGlzLT5MYW5nKCJwaXhlbHMiKSk7CgokdGhpcy0+c21hcnR5LT5hc3NpZ24oInN0eWxld2lkdGh0ZXh0IiwkdGhpcy0+TGFuZygic3R5bGV3aWR0aHRleHQiKSk7CiR0aGlzLT5zbWFydHktPmFzc2lnbigic3R5bGV3aWR0aGlucHV0IiwKJHRoaXMtPkNyZWF0ZUlucHV0VGV4dCgkaWQsInN0eWxpc3R3aWR0aCIsJHN0eWxpc3R3aWR0aCwnOCcsJzYnKS4KJHRoaXMtPkxhbmcoInBpeGVscyIpKTsKCiRmbGF2b3JzPWFycmF5KCR0aGlzLT5MYW5nKCJocmVmZmxhdm9yIik9PiJocmVmIik7CiR0aGlzLT5zbWFydHktPmFzc2lnbigibGlua2VyZmxhdm9ydGV4dCIsJHRoaXMtPkxhbmcoImxpbmtlcmZsYXZvciIpKTsKJHRoaXMtPnNtYXJ0eS0+YXNzaWduKCJsaW5rZXJmbGF2b3JpbnB1dCIsJHRoaXMtPkNyZWF0ZUlucHV0RHJvcGRvd24oJGlkLCJsaW5rZXJmbGF2b3IiLCRmbGF2b3JzLC0xLCRsaW5rZXJmbGF2b3IpKTsKCiR0aGlzLT5zbWFydHktPmFzc2lnbigiYWJzb2x1dGV1cmxzdGV4dCIsJHRoaXMtPkxhbmcoImFic29sdXRldXJscyIpKTsKJHRoaXMtPnNtYXJ0eS0+YXNzaWduKCJhYnNvbHV0ZXVybHNpbnB1dCIsJHRoaXMtPkNyZWF0ZUlucHV0Q2hlY2tib3goJGlkLCJhYnNvbHV0ZXVybHMiLCcxJywkYWJzb2x1dGV1cmxzKSk7CgokdGhpcy0+c21hcnR5LT5hc3NpZ24oInJlcGxhY2Vyb290dXJsc3RleHQiLCAkdGhpcy0+TGFuZygicmVwbGFjZXJvb3R1cmxzIikpOwokdGhpcy0+c21hcnR5LT5hc3NpZ24oInJlcGxhY2Vyb290dXJsc2lucHV0IiwkdGhpcy0+Q3JlYXRlSW5wdXRDaGVja2JveCgkaWQsInJlcGxhY2Vyb290dXJscyIsJzEnLCRyZXBsYWNlcm9vdHVybHMpKTsKCiR0aGlzLT5zbWFydHktPmFzc2lnbigiYm9keWNzc3RleHQiLCAkdGhpcy0+TGFuZygiYm9keWNzcyIpKTsKJHRoaXMtPnNtYXJ0eS0+YXNzaWduKCJib2R5Y3NzaW5wdXQiLCAkdGhpcy0+Q3JlYXRlSW5wdXRUZXh0KCRpZCwiYm9keWNzcyIsJGJvZHljc3MsNjApLiR0aGlzLT5MYW5nKCJ2YWxpZGNzcyIpKTsKCgokdGhpcy0+c21hcnR5LT5hc3NpZ24oInN1Ym1pdCIsJHRoaXMtPkNyZWF0ZUlucHV0U3VibWl0KCRpZCwic3VibWl0IiwkdGhpcy0+TGFuZygib2siKSkpOwokdGhpcy0+c21hcnR5LT5hc3NpZ24oImNhbmNlbCIsJHRoaXMtPkNyZWF0ZUlucHV0U3VibWl0KCRpZCwiY2FuY2VsIiwkdGhpcy0+TGFuZygiY2FuY2VsIikpKTsKCiR0aGlzLT5zbWFydHktPmFzc2lnbigicHJldmlldyIsCiAgJHRoaXMtPkxhbmcoImV4YW1wbGUiKS4KICAiOjxici8+Ii4KICAkdGhpcy0+Q3JlYXRlVGV4dEFyZWEodHJ1ZSwkaWQsJHRoaXMtPkxhbmcoInRlc3RpbmdhcmVhIiksImV4YW1wbGUiLCcnLCcnLCcnLCJzdHlsZS5waHAiLDgwLDE1LCJYaW5oYSIpKTsKCmVjaG8gJHRoaXMtPlByb2Nlc3NUZW1wbGF0ZSgnc2V0dGluZ3MudHBsJyk7CgplY2hvICR0aGlzLT5FbmRUYWIoKTsKZWNobyAkdGhpcy0+U3RhcnRUYWIoInBsdWdpbnMiKTsKCmVjaG8gJHRoaXMtPkNyZWF0ZUZvcm1TdGFydCgkaWQsInNhdmVwbHVnaW5zIik7CgplY2hvICI8dGFibGU+IjsKc29ydCgkcGx1Z2luc19hdmFpbGFibGUpOwpmb3IgKCRpPTA7ICRpPGNvdW50KCRwbHVnaW5zX2F2YWlsYWJsZSk7ICRpKyspIHsKCWVjaG8gIjx0cj48dGQ+IjsKCSRzZWxlY3RlZD0wOwoJaWYgKEBlcmVnaSgkcGx1Z2lucywkcGx1Z2luc19hdmFpbGFibGVbJGldKSE9PWZhbHNlKSAkc2VsZWN0ZWQ9MTsKCWVjaG8gJHRoaXMtPkNyZWF0ZUlucHV0Q2hlY2tib3goJGlkLCJwbHVnaW5fIi4kcGx1Z2luc19hdmFpbGFibGVbJGldLCIxIiwkc2VsZWN0ZWQpOwoJZWNobyAkcGx1Z2luc19hdmFpbGFibGVbJGldOwoJZWNobyAiPC90ZD48dGQ+IjsKCWlmICgkaTxjb3VudCgkcGx1Z2luc19hdmFpbGFibGUpLTEpIHsKCQkkaSsrOwoJCSRzZWxlY3RlZD0wOwoJCWlmIChAZXJlZ2koJHBsdWdpbnMsJHBsdWdpbnNfYXZhaWxhYmxlWyRpXSkhPT1mYWxzZSkgJHNlbGVjdGVkPTE7CgkJZWNobyAkdGhpcy0+Q3JlYXRlSW5wdXRDaGVja2JveCgkaWQsInBsdWdpbl8iLiRwbHVnaW5zX2F2YWlsYWJsZVskaV0sIjEiLCRzZWxlY3RlZCk7CgkJZWNobyAkcGx1Z2luc19hdmFpbGFibGVbJGldOwoJfSBlbHNlIGVjaG8gIiZuYnNwOyI7CgoJZWNobyAiPC90ZD48L3RyPiI7Cn0KZWNobyAiPC90YWJsZT4iOwplY2hvICR0aGlzLT5DcmVhdGVJbnB1dFN1Ym1pdCgkaWQsInN1Ym1pdCIsJHRoaXMtPkxhbmcoIm9rIikpOwplY2hvICR0aGlzLT5DcmVhdGVGb3JtRW5kKCk7CmVjaG8gJHRoaXMtPkVuZFRhYigpOwplY2hvICR0aGlzLT5FbmRUYWJDb250ZW50KCk7Cj8+]]></data>
	</file>
	<file>
	  <filename>/action.saveplugins.php</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[PD9waHAKLy9TY2FuIGZvciBhdmFpbGFibGUgcGx1Z2lucwokcGx1Z2luc19hdmFpbGFibGUgPSBBcnJheSgpOwokZCA9IGRpcihkaXJuYW1lKF9fRklMRV9fKS4nL3hpbmhhL3BsdWdpbnMnKTsKd2hpbGUgKCRlbnRyeSA9ICRkLT5yZWFkKCkpIHsKCWlmICgkZW50cnlbMF0hPScuJykgewoJCSRwbHVnaW5zX2F2YWlsYWJsZVtdPXRyaW0oJGVudHJ5KTsKCX0KfQokcGx1Z2lucz0iIjsKZm9yICgkaT0wOyAkaTxjb3VudCgkcGx1Z2luc19hdmFpbGFibGUpOyRpKyspIHsKICBpZiAoaXNzZXQoJHBhcmFtc1sncGx1Z2luXycuJHBsdWdpbnNfYXZhaWxhYmxlWyRpXV0pKSB7CiAgICBpZiAoJHBhcmFtc1sncGx1Z2luXycuJHBsdWdpbnNfYXZhaWxhYmxlWyRpXV09PSIxIikgewogICAgICBpZiAoJHBsdWdpbnM9PSIiKSAkcGx1Z2lucz0kcGx1Z2luc19hdmFpbGFibGVbJGldOyBlbHNlICRwbHVnaW5zLj0ifCIuJHBsdWdpbnNfYXZhaWxhYmxlWyRpXTsKCQl9Cgl9Cn0KJHRoaXMtPlNldFByZWZlcmVuY2UoIlhpbmhhLlBsdWdpbnMiLCRwbHVnaW5zKTsKJG1lc3NhZ2U9JHRoaXMtPkxhbmcoIm5ld3BsdWdpbnMiKTsKJGFjdGlvbj0iZGVmYXVsdGFkbWluIjsKJHRoaXMtPlJlZGlyZWN0KCRpZCwkYWN0aW9uLCRyZXR1cm5pZCxhcnJheSgibW9kdWxlX21lc3NhZ2UiPT4kbWVzc2FnZSwidGFiIj0+InBsdWdpbnMiKSk7CQkKPz4=]]></data>
	</file>
	<file>
	  <filename>/action.savesettings.php</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[PD9waHAKaWYgKCFpc3NldCgkZ0NtcykgfHwgISR0aGlzLT5WaXNpYmxlVG9BZG1pblVzZXIoKSkgZXhpdDsKCmlmIChpc3NldCgkcGFyYW1zWydza2luJ10pKQkkdGhpcy0+U2V0UHJlZmVyZW5jZSgnWGluaGEuU2tpbicsICRwYXJhbXNbJ3NraW4nXSk7CmlmIChpc3NldCgkcGFyYW1zWyd3aWR0aCddKSkgJHRoaXMtPlNldFByZWZlcmVuY2UoJ1hpbmhhLldpZHRoJywgJHBhcmFtc1snd2lkdGgnXSk7CmlmIChpc3NldCgkcGFyYW1zWyd3aWR0aGF1dG8nXSkpICR0aGlzLT5TZXRQcmVmZXJlbmNlKCdYaW5oYS5XaWR0aEF1dG8nLCAnMScpOyBlbHNlICR0aGlzLT5TZXRQcmVmZXJlbmNlKCdYaW5oYS5XaWR0aEF1dG8nLCAnMCcpOwppZiAoaXNzZXQoJHBhcmFtc1snaGVpZ2h0J10pKQkkdGhpcy0+U2V0UHJlZmVyZW5jZSgnWGluaGEuSGVpZ2h0JywgJHBhcmFtc1snaGVpZ2h0J10pOwppZiAoaXNzZXQoJHBhcmFtc1snaGVpZ2h0YXV0byddKSkJJHRoaXMtPlNldFByZWZlcmVuY2UoJ1hpbmhhLkhlaWdodEF1dG8nLCAnMScpOyBlbHNlICR0aGlzLT5TZXRQcmVmZXJlbmNlKCdYaW5oYS5IZWlnaHRBdXRvJywgJzAnKTsKCmlmIChpc3NldCgkcGFyYW1zWyd3aWR0aHVuaXQnXSkpJHRoaXMtPlNldFByZWZlcmVuY2UoJ1hpbmhhLldpZHRoVW5pdCcsICRwYXJhbXNbJ3dpZHRodW5pdCddKTsKCmlmIChpc3NldCgkcGFyYW1zWydzdHlsaXN0d2lkdGgnXSkpCSR0aGlzLT5TZXRQcmVmZXJlbmNlKCdYaW5oYS5TdHlsaXN0V2lkdGgnLCAkcGFyYW1zWydzdHlsaXN0d2lkdGgnXSk7CgppZiAoaXNzZXQoJHBhcmFtc1snYm9keWNzcyddKSkgJHRoaXMtPlNldFByZWZlcmVuY2UoJ1hpbmhhLkJvZHlDU1MnLCAkcGFyYW1zWydib2R5Y3NzJ10pOwoKaWYgKGlzc2V0KCRwYXJhbXNbJ2Fic29sdXRldXJscyddKSkgJHRoaXMtPlNldFByZWZlcmVuY2UoJ1hpbmhhLkFic29sdXRlVXJscycsICRwYXJhbXNbJ2Fic29sdXRldXJscyddKTsgZWxzZSAkdGhpcy0+U2V0UHJlZmVyZW5jZSgnWGluaGEuQWJzb2x1dGVVcmxzJywgJzAnKTsKaWYgKGlzc2V0KCRwYXJhbXNbJ3JlcGxhY2Vyb290dXJscyddKSkgJHRoaXMtPlNldFByZWZlcmVuY2UoJ1hpbmhhLlJlcGxhY2VSb290VXJscycsICRwYXJhbXNbJ3JlcGxhY2Vyb290dXJscyddKTsgZWxzZSAkdGhpcy0+U2V0UHJlZmVyZW5jZSgnWGluaGEuUmVwbGFjZVJvb3RVcmxzJywgJzAnKTsKCiRhY3Rpb249ImRlZmF1bHRhZG1pbiI7CiRtZXNzYWdlPSR0aGlzLT5MYW5nKCJzZXR0aW5nc3NhdmVkIik7CgokdGhpcy0+UmVkaXJlY3QoJGlkLCJkZWZhdWx0YWRtaW4iLCRyZXR1cm5pZCxhcnJheSgibW9kdWxlX21lc3NhZ2UiPT4kdGhpcy0+TGFuZygic2V0dGluZ3NzYXZlZCIpKSk7Cj8+]]></data>
	</file>
	<file>
	  <filename>/editorarea.css.php</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[PD9waHAKaGVhZGVyKCJDb250ZW50LVR5cGU6IHRleHQvY3NzIik7CgokaW5jbGZpbGVuYW1lID0gJy4uL2luY2x1ZGUucGhwJzsKd2hpbGUoIUBmaWxlX2V4aXN0cygkaW5jbGZpbGVuYW1lKSkgewogICRpbmNsZmlsZW5hbWUgPSAiLi4vIi4kaW5jbGZpbGVuYW1lOwp9CkByZXF1aXJlX29uY2UoJGluY2xmaWxlbmFtZSk7CgpnbG9iYWwgJGdDbXM7CgppZiAoaXNzZXQoJF9HRVRbImlkIl0pKQogICRpZCA9ICRfR0VUWyJpZCJdOwplbHNlCiAgJGlkID0gMTsKCiRjc3MgPSAnJzsKZm9yZWFjaCAoZ2V0X3N0eWxlc2hlZXRfbWVkaWFfdHlwZXMoJGlkKSBhcyAkbWVkaWEpCnsKICAkcmVzID0gZ2V0X3N0eWxlc2hlZXQoJGlkLCAkbWVkaWEpOwogICRjc3MgLj0gJHJlc1sic3R5bGVzaGVldCJdOwp9CgokYm9keWNzcz0kZ0Ntcy0+bW9kdWxlc1siWGluaGEiXVsnb2JqZWN0J10tPkdldFByZWZlcmVuY2UoIlhpbmhhLkJvZHlDU1MiKTsKaWYgKCRib2R5Y3NzIT0iIikgewogICRjc3MuPSIKICBib2R5IHsKICAgICIuJGJvZHljc3MuIgogIH0KICAiOwp9CmVjaG8gJGNzczsKPz4=]]></data>
	</file>
	<file>
	  <filename>/genonload.js</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[PD9waHAKLy9HTzEuMQoKCi8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLwovLwovLyAgR2VuZXJpYyBvbmxvYWQgYnkgQnJvdGhlcmNha2UKLy8gIGh0dHA6Ly93d3cuYnJvdGhlcmNha2UuY29tLwovLwovLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8KCi8vb25sb2FkIGZ1bmN0aW9uCmZ1bmN0aW9uIGdlbmVyaWMoKQp7CglhbGVydCgnaGknKTsKICB4aW5oYV9pbml0KCk7Cn0KCi8vc2V0dXAgb25sb2FkIGZ1bmN0aW9uCmlmKHR5cGVvZiB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lciAhPSAndW5kZWZpbmVkJykKewogICAgLy8uLiBnZWNrbywgc2FmYXJpLCBrb25xdWVyb3IgYW5kIHN0YW5kYXJkCiAgICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIGdlbmVyaWMsIGZhbHNlKTsKfQplbHNlIGlmKHR5cGVvZiBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyICE9ICd1bmRlZmluZWQnKQp7CiAgICAvLy4uIG9wZXJhIDcKICAgIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCBnZW5lcmljLCBmYWxzZSk7Cn0KZWxzZSBpZih0eXBlb2Ygd2luZG93LmF0dGFjaEV2ZW50ICE9ICd1bmRlZmluZWQnKQp7CiAgICAvLy4uIHdpbi9pZQogICAgd2luZG93LmF0dGFjaEV2ZW50KCdvbmxvYWQnLCBnZW5lcmljKTsKfQoKLy8qKiByZW1vdmUgdGhpcyBjb25kaXRpb24gdG8gZGVncmFkZSBvbGRlciBicm93c2VycwplbHNlCnsKICAgIC8vLi4gbWFjL2llNSBhbmQgYW55dGhpbmcgZWxzZSB0aGF0IGdldHMgdGhpcyBmYXIKICAgIAogICAgLy9pZiB0aGVyZSdzIGFuIGV4aXN0aW5nIG9ubG9hZCBmdW5jdGlvbgogICAgaWYodHlwZW9mIHdpbmRvdy5vbmxvYWQgPT0gJ2Z1bmN0aW9uJykKICAgIHsKICAgICAgICAvL3N0b3JlIGl0CiAgICAgICAgdmFyIGV4aXN0aW5nID0gb25sb2FkOwogICAgICAgIAogICAgICAgIC8vYWRkIG5ldyBvbmxvYWQgaGFuZGxlcgogICAgICAgIHdpbmRvdy5vbmxvYWQgPSBmdW5jdGlvbigpCiAgICAgICAgewogICAgICAgICAgICAvL2NhbGwgZXhpc3Rpbmcgb25sb2FkIGZ1bmN0aW9uCiAgICAgICAgICAgIGV4aXN0aW5nKCk7CiAgICAgICAgICAgIAogICAgICAgICAgICAvL2NhbGwgZ2VuZXJpYyBvbmxvYWQgZnVuY3Rpb24KICAgICAgICAgICAgZ2VuZXJpYygpOwogICAgICAgIH07CiAgICB9CiAgICBlbHNlCiAgICB7CiAgICAgICAgLy9zZXR1cCBvbmxvYWQgZnVuY3Rpb24KICAgICAgICB3aW5kb3cub25sb2FkID0gZ2VuZXJpYzsKICAgIH0KfQo/PiA=]]></data>
	</file>
	<file>
	  <filename>/lang/</filename>
	  <isdir>1</isdir>
	</file>
	<file>
	  <filename>/lang/en_US.php</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[PD9waHAKJGxhbmdbJ3NldHRpbmdzJ109IlNldHRpbmdzIjsKJGxhbmdbJ3Blcm1pc3Npb24nXSA9ICdVc2UgWGluaGEnOwokbGFuZ1sncGx1Z2lucyddPSJQbHVnaW5zIjsKJGxhbmdbJ3NlbGVjdHNraW4nXT0iU2VsZWN0IHNraW4iOwokbGFuZ1snc2VsZWN0d2lkdGgnXT0iV2lkdGggb2YgZWRpdG9yIjsKJGxhbmdbJ3NlbGVjdGhlaWdodCddPSJIZWlnaHQgb2YgZWRpdG9yIjsKJGxhbmdbJ2F1dG8nXT0iQXV0by1kZXRlY3QsIG9yIHNldCB0bzogIjsKJGxhbmdbJ3NlbGVjdHN0eWxld2lkdGgnXT0iV2lkdGggb2Ygc3R5bGlzdCBwbHVnaW4iOwokbGFuZ1snZXhhbXBsZSddPSJFeGFtcGxlIHRleHRhcmVhIjsKJGxhbmdbJ3BpeGVscyddPSJQaXhlbHMiOwokbGFuZ1snYm9keWNzcyddPSJCb2R5IENTUyI7CiRsYW5nWydsaW5rZXJmbGF2b3InXT0iQ01TTVNMaW5rZXIgc3R5bGUiOwokbGFuZ1snaHJlZmZsYXZvciddPSJHZW5lcmF0ZSBzdGFuZGFyZCBocmVmLXN0eWxlIGxpbmtzIjsKJGxhbmdbJ3NlbGZsaW5rZmxhdm9yJ109IkdlbmVyYXRlIENNU01TLXNlbGZsaW5rLXN0eWxlIGxpbmtzIjsKJGxhbmdbJ3ZhbGlkY3NzJ109Ildhcm5pbmchIHRoaXMgbXVzdCBiZSB2YWxpZCBDU1Mtc3RhdGVtZW50cyI7CiRsYW5nWydvayddPSJPSyI7CiRsYW5nWydjYW5jZWwnXT0iQ2FuY2VsIjsKJGxhbmdbJ3Rlc3RpbmdhcmVhJ109IlRoaXMgaXMgYSB0ZXN0aW5nIGFyZWEsIG5vIGNvbnRlbnQgd2lsbCBiZSBoYXJtZWQgaW4gY2FzZSBvZiB1bmludGVudGlvbmFsIGNoYW5nZXMiOwokbGFuZ1sncG9zdGluc3RhbGwnXT0iTW9kdWxlIHN1Y2Nlc3NmdWxseSBpbnN0YWxsZWQhIFNldCB0aGUgJ01vZGlmeSBYaW5oYS1zZXR0aW5ncycgcGVybWlzc2lvbiB0byBhbGxvdyBjdXN0b21pemF0aW9uLiI7CiRsYW5nWydzdHlsZXdpZHRodGV4dCddPSJXaWR0aCBvZiBzdHlsZSBsaXN0IjsKCiRsYW5nWyJza2luIl09IlNraW4iOwokbGFuZ1snYWJzb2x1dGV1cmxzJ109IlVzZSBhYnNvbHV0ZSBVUkxzPyI7CiRsYW5nWydyZXBsYWNlcm9vdHVybHMnXT0iUmVwbGFjZSByb290IHdpdGggU21hcnR5LXRhZz8iOwokbGFuZ1snc2V0dGluZ3NzYXZlZCddPSJTZXR0aW5ncyBzYXZlZCI7CiRsYW5nWyduZXdwbHVnaW5zJ109IlNlbGVjdGVkIHBsdWdpbnMgZW5hYmxlZCI7CiRsYW5nWydub2FjY2VzcyddPSJZb3UgbmVlZCB0aGUgJXMgcGVybWlzc2lvbiB0byBwZXJmb3JtIHRoYXQgZnVuY3Rpb24hIjsKJGxhbmdbJ2hlbHAnXT08PDxFT0YKPGgzPldoYXQgZG9lcyB0aGlzIGRvPzwvaDM+CiAgICA8cD5FbmFibGVzIDxiPlhpbmhhPC9iPiB0byBiZSB1c2VkIGFzIGEgV1lTSVdZRy48L3A+CiAgICA8aDM+SG93IGRvIEkgdXNlIGl0PzwvaDM+CiAgICA8cD5JbnN0YWxsIGl0LCB0aGVuIGdvIHRvIFVzZXIgUHJlZmVyZW5jZXMgYW5kIFNldCA8Yj5YaW5oYTwvYj4gdG8gYmUgeW91ciB3eXNpd3lnIG9mIGNob2ljZS48L3A+JzsKICAgIDxwPlRvIGN1c3RvbWl6ZSBpdCB0aGUgcGVybWlzc2lvbiA8aT5Nb2RpZnkgWGluaGEtc2V0dGluZ3M8L2k+IG11c3QgYmUgc2V0IGZvciB5b3UgZ3JvdXAuPC9wPgpFT0Y7CgokbGFuZ1snY2hhbmdlbG9nJ109PDw8RU9GCgkJPHVsPgoJCTxsaT4KICAJPHA+VmVyc2lvbjogMC4xLjQ8L3A+CiAgCTxwPkZpeGVkIFJlY29yZENvdW50LWNhbGxzPC9wPgogIAk8cD5VcGRhdGVkIHRvIGxhdGVzdCBzdm48L3A+CgkJPGxpPgogIAk8cD5WZXJzaW9uOiAwLjEuMzwvcD4KICAJPHA+TWFkZSBpdCBvcHRpb25hbCB3aGV0aGVyIGFib3NsdXRlIG9yIHJlbGF0aXZlIGxpbmtzIHNob3VsZCBiZSBnZW5lcmF0ZWQ8L3A+CiAgCTxwPkFsbG93ZWQgdGhlIHJvb3QgdG8gYmUgcmVwbGFjZWQgd2l0aCB0aGUge3Jvb3RfdXJsfS1wbHVnaW50YWcgKG5vdCBmaW5pc2hlZCk8L3A+CiAgCTxwPkZpeGVkIHJlbW92aW5nIHNldHRpbmcgdXBvbiB1bmluc3RhbGw8L3A+CgkJPHA+UHJlcGFyZWQgaXQgdG8gYmUgb3B0aW9uYWwgd2hldGhlciB0aGUgY21zbXNsaW5rZXIgc2hvdWxkIGdlbmVyYXRlIGhyZWYtc3R5bGUgb3Ige2Ntcy1zZWxmbGlua30tc3R5bGUgbGlua3MgKE5PVCB3b3JraW5nIHlldCk8L3A+CgkJPC9saT4KCQk8bGk+CgkJPHA+VmVyc2lvbjogMC4xLjI8L3A+CgkJPHA+QWRkZWQgcGVybWlzc2lvbiB0byBjaGFuZ2Ugc2V0dGluZ3M8L3A+CgkJPHA+QWRkZWQgYSBDTVMtbGlua2VyIG1vZHVsZSB0byBYaW5oYTwvcD4KCQk8cD5BZGRlZCB0aGUgTXVsdGlDb25maWd1cmF0aW9uIHBsdWdpbiB0byBYaW5oYTwvcD4KCQk8L2xpPgoJCTxsaT4KCQk8cD5WZXJzaW9uOiAwLjEuMTwvcD4KCQk8cD5GaXhlZCBhdXRvZGV0ZWN0aW9uIG9mIFN3ZWRpc2g8L3A+CgkJPHA+Rml4ZWQgdGhlIHByb2JsZW0gd2l0aCBoYW5naW5nIGZvcm0tYnV0dG9ucyB3aGVuIGluIGZ1bGxzY3JlZW4gbW9kZTwvcD4KCQk8cD5ObyB1Z2x5IGhlYWRlciBzdHVmZiBpbnNlcnRlZCBpbnRvIHBhZ2VzIG5vdCBjb250YWluaW5nIGEgJ3RleHRhcmVhJyB0YWc8L3A+CgkJPHA+Rml4ZWQgWGluaGEgbm90IHNob3dpbmcgd2hlbiBlZGl0aW5nIG5ld3MuLi48L3A+CgkJPHA+QWRkZWQgd2lkdGggb2YgZWRpdG9yLWFyZWEgYXMgYW4gb3B0aW9uPC9wPgoJCTxwPkFkZGVkIGEgZXhhbXBsZSB0ZXh0LWFyZWE8L3A+CgkJPHA+QWRkZWQgd2lkdGggb2YgdGhlIFN0eWxpc3QgcGFuZWwgYXMgYW4gb3B0aW9uPC9wPgogICAgPHA+Rml4ZWQgc2hvcnRfb3Blbl90YWdzPC9wPgogICAgPHA+PC9wPgoJCTwvbGk+CgkJPGxpPgoJCTxwPlZlcnNpb246IDAuMS4wPC9wPgoJCTxwPkZpcnN0IHZlcnNpb24gcmVsZWFzZWQgb3V0c2lkZSBzdm48L3A+CgkJPHA+Rml4ZWQgcmVsYXRpdmUgaW1hZ2Utc291cmNlczwvcD4KCQk8cD5Ob3cgc2hvd3MgdGhlIHN0eWxlc2hlZXQgb2YgdGhlIHBhZ2UgaWYgdGhlIHBsdWdpbiBTdHlsaXN0IGlzIGVuYWJsZWQgKGl0IGlzIGJ5IGRlZmF1bHQpPC9wPgoJCTwvbGk+CgkJPGxpPgoJCTxwPlZlcnNpb246IDAuMC4yPC9wPgoJCTxwPkZpeGVkIGEgcHJvYmxlbSB3aGljaCBhZmZlY3RlZCB0aGUgdGFicyBvbiBhbGwgYWRtaW4tcGFnZXM8L3A+CgkJPHA+Rml4ZWQgc29tZSBwaHA1LXJlbGF0ZWQgcHJvYmxlbXM8L3A+CgkJPHA+VGhlIG1vZHVsZSBub3cgdHJpZXMgdG8gZmlndXJlIG91dCB5b3VyIGxhbmd1YWdlIHByZWZlcmVuY2UgYW5kIGFkanVzdCB0byB0aGF0PC9wPgoJCTwvbGk+CgkJPGxpPgoJCTxwPlZlcnNpb246IDAuMC4xPC9wPgoJCTxwPkluaXRpYWwgdGVzdCByZWxlYXNlLjwvcD4KCQk8L2xpPgoJCTwvdWw+CkVPRjsKPz4=]]></data>
	</file>
	<file>
	  <filename>/lang/ext/</filename>
	  <isdir>1</isdir>
	</file>
	<file>
	  <filename>/lang/ext/cs_CZ.php</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[PD9waHAKJGxhbmdbJ3NldHRpbmdzJ10gPSAnTmFzdGF2ZW4maWFjdXRlOyc7CiRsYW5nWydwbHVnaW5zJ10gPSAnUm96JnNjYXJvbjsmaWFjdXRlO8WZZW4maWFjdXRlOyc7CiRsYW5nWydzZWxlY3Rza2luJ10gPSAnVnliZXIgdnpobGVkJzsKJGxhbmdbJ3NlbGVjdHdpZHRoJ10gPSAnJlNjYXJvbjsmaWFjdXRlO8WZa2EgZWRpdG9ydSc7CiRsYW5nWydzZWxlY3RoZWlnaHQnXSA9ICdWJnlhY3V0ZTsmc2Nhcm9uO2thIGVkaXRvcnUnOwokbGFuZ1snYXV0byddID0gJ1pqaXN0aSBhdXRvbWF0aWNreSAsIG5lYm8gbmFzdGF2IG5hOiAnOwokbGFuZ1snc2VsZWN0c3R5bGV3aWR0aCddID0gJyZTY2Fyb247JmlhY3V0ZTvFmWthIHJveiZzY2Fyb247JmlhY3V0ZTvFmWVuJmlhY3V0ZTsgU3R5bGlzdCc7CiRsYW5nWydleGFtcGxlJ10gPSAnUMWZJmlhY3V0ZTtrbGFkIHRleHRvdiZlYWN1dGU7aG8gcG9sZSc7CiRsYW5nWydwaXhlbHMnXSA9ICdQaXhlbHknOwokbGFuZ1snYm9keWNzcyddID0gJ0JvZHkgQ1NTJzsKJGxhbmdbJ2xpbmtlcmZsYXZvciddID0gJ1N0eWwgQ01TTVNMaW5rZXInOwokbGFuZ1snaHJlZmZsYXZvciddID0gJ0dlbmVydWogc3RhbmRhcmRuJmlhY3V0ZTsgb2RrYXp5IHR5cHUgaHJlZic7CiRsYW5nWydzZWxmbGlua2ZsYXZvciddID0gJ0dlbmVydWogb2RrYXp5IHR5cHUgQ01TTVMtc2VsZmxpbmsnOwokbGFuZ1sndmFsaWRjc3MnXSA9ICdQb3pvciEgVG90byBtdXMmaWFjdXRlOyBiJnlhY3V0ZTt0IHBsYXRuJnlhY3V0ZTsgeiZhYWN1dGU7cGlzIENTUyc7CiRsYW5nWydvayddID0gJ09LJzsKJGxhbmdbJ3Rlc3RpbmdhcmVhJ10gPSAnVG90byBqZSBwcm9zdG9yIHBybyBwb2t1c3ksIHYgcMWZJmlhY3V0ZTtwYWTEmyBuZWNodMSbbiZ5YWN1dGU7Y2ggem3Em24gbmVidWRlIHBvJnNjYXJvbjtrb3plbiDFviZhYWN1dGU7ZG4meWFjdXRlOyBvYnNhaC4nOwokbGFuZ1sncG9zdGluc3RhbGwnXSA9ICdNb2R1bCAmdWFjdXRlO3NwxJsmc2Nhcm9uO27EmyBuYWluc3RhbG92JmFhY3V0ZTtuISBOYXN0YXYgJiMwMzk7TW9kaWZ5IFhpbmhhLXNldHRpbmdzJiMwMzk7IG9wciZhYWN1dGU7dm7Em24maWFjdXRlOyBwcm8gcG92b2xlbiZpYWN1dGU7IHptxJtuIG5hc3RhdmVuJmlhY3V0ZTsuJzsKJGxhbmdbJ2Fic29sdXRldXJscyddID0gJ1BvdcW+JmlhY3V0ZTt0IGFic29sdXRuJmlhY3V0ZTsgYWRyZXN5IChVUkwpPyc7CiRsYW5nWydyZXBsYWNlcm9vdHVybHMnXSA9ICdSZXBsYWNlIHJvb3Qgd2l0aCBTbWFydHktdGFnPyc7CiRsYW5nWydzZXR0aW5nc3NhdmVkJ10gPSAnTmFzdGF2ZW4maWFjdXRlOyB1bG/FvmVuYSc7CiRsYW5nWyduZXdwbHVnaW5zJ10gPSAnVnlicmFuJmVhY3V0ZTsgcm96JnNjYXJvbjsmaWFjdXRlO8WZZW4maWFjdXRlOyBwb3ZvbGVubyc7CiRsYW5nWydub2FjY2VzcyddID0gJ1BvdMWZZWJ1amV0ZSAlcyBvcHImYWFjdXRlO3ZuxJtuJmlhY3V0ZTsgcHJvIHZ5a29uJmFhY3V0ZTtuJmlhY3V0ZTsgdCZlYWN1dGU7dG8gZnVua2NlISc7CiRsYW5nWydoZWxwJ10gPSAnPGgzPkNvIHRlbnRvIG1vZHVsIGTEm2wmYWFjdXRlOz88L2gzPg0KICAgIDxwPlVtb8W+xYh1amUgdnl1xb4maWFjdXRlO3QgZWRpdG9ydSA8Yj5YaW5oYTwvYj4gamFrbyBXWVNJV1lHIGVkaXRvcnUgQ01TTVMuPC9wPg0KICAgIDxoMz5KYWsgaG8gbW9odSBwb3XFviZpYWN1dGU7dD88L2gzPg0KICAgIDxwPk5haW5zdGFsdWp0ZSBobyBhIHBvdCZlYWN1dGU7IGhvIG5hc3RhdnRlIHYgTSZhYWN1dGU7IG5hc3RhdmVuJmlhY3V0ZTsgLT4gTmFzdGF2ZW4maWFjdXRlOyBhZG1pbmlzdHJhY2UgamFrbyB2JnlhY3V0ZTtjaG96JmlhY3V0ZTsgZWRpdG9yLjwvcD4mIzAzOTs7DQogICAgPHA+UHJvIG5hc3RhdmVuJmlhY3V0ZTsgZWRpdG9ydSB1ZMSbbHRlIG9wciZhYWN1dGU7dm7Em24maWFjdXRlOyA8aT5Nb2RpZnkgWGluaGEtc2V0dGluZ3M8L2k+IHDFmSZpYWN1dGU7c2x1JnNjYXJvbjtuJmVhY3V0ZTsgc2t1cGluxJsgdiBkaWFsb2d1IFXFvml2YXRlbCZlYWN1dGU7L1NrdXBpbnkgLT4gT3ByJmFhY3V0ZTt2bsSbbiZpYWN1dGU7IHNrdXBpbnkuPC9wPic7CiRsYW5nWydjaGFuZ2Vsb2cnXSA9ICcJCTx1bD4NCgkJPGxpPg0KICAJPHA+VmVyc2lvbjogMC4xLjM8L3A+DQogIAk8cD5NYWRlIGl0IG9wdGlvbmFsIHdoZXRoZXIgYWJvc2x1dGUgb3IgcmVsYXRpdmUgbGlua3Mgc2hvdWxkIGJlIGdlbmVyYXRlZDwvcD4NCiAgCTxwPkFsbG93ZWQgdGhlIHJvb3QgdG8gYmUgcmVwbGFjZWQgd2l0aCB0aGUge3Jvb3RfdXJsfS1wbHVnaW50YWcgKG5vdCBmaW5pc2hlZCk8L3A+DQogIAk8cD5GaXhlZCByZW1vdmluZyBzZXR0aW5nIHVwb24gdW5pbnN0YWxsPC9wPg0KCQk8cD5QcmVwYXJlZCBpdCB0byBiZSBvcHRpb25hbCB3aGV0aGVyIHRoZSBjbXNtc2xpbmtlciBzaG91bGQgZ2VuZXJhdGUgaHJlZi1zdHlsZSBvciB7Y21zLXNlbGZsaW5rfS1zdHlsZSBsaW5rcyAoTk9UIHdvcmtpbmcgeWV0KTwvcD4NCgkJPC9saT4NCgkJPGxpPg0KCQk8cD5WZXJzaW9uOiAwLjEuMjwvcD4NCgkJPHA+QWRkZWQgcGVybWlzc2lvbiB0byBjaGFuZ2Ugc2V0dGluZ3M8L3A+DQoJCTxwPkFkZGVkIGEgQ01TLWxpbmtlciBtb2R1bGUgdG8gWGluaGE8L3A+DQoJCTxwPkFkZGVkIHRoZSBNdWx0aUNvbmZpZ3VyYXRpb24gcGx1Z2luIHRvIFhpbmhhPC9wPg0KCQk8L2xpPg0KCQk8bGk+DQoJCTxwPlZlcnNpb246IDAuMS4xPC9wPg0KCQk8cD5GaXhlZCBhdXRvZGV0ZWN0aW9uIG9mIFN3ZWRpc2g8L3A+DQoJCTxwPkZpeGVkIHRoZSBwcm9ibGVtIHdpdGggaGFuZ2luZyBmb3JtLWJ1dHRvbnMgd2hlbiBpbiBmdWxsc2NyZWVuIG1vZGU8L3A+DQoJCTxwPk5vIHVnbHkgaGVhZGVyIHN0dWZmIGluc2VydGVkIGludG8gcGFnZXMgbm90IGNvbnRhaW5pbmcgYSAmIzAzOTt0ZXh0YXJlYSYjMDM5OyB0YWc8L3A+DQoJCTxwPkZpeGVkIFhpbmhhIG5vdCBzaG93aW5nIHdoZW4gZWRpdGluZyBuZXdzLi4uPC9wPg0KCQk8cD5BZGRlZCB3aWR0aCBvZiBlZGl0b3ItYXJlYSBhcyBhbiBvcHRpb248L3A+DQoJCTxwPkFkZGVkIGEgZXhhbXBsZSB0ZXh0LWFyZWE8L3A+DQoJCTxwPkFkZGVkIHdpZHRoIG9mIHRoZSBTdHlsaXN0IHBhbmVsIGFzIGFuIG9wdGlvbjwvcD4NCiAgICA8cD5GaXhlZCBzaG9ydF9vcGVuX3RhZ3M8L3A+DQogICAgPHA+PC9wPg0KCQk8L2xpPg0KCQk8bGk+DQoJCTxwPlZlcnNpb246IDAuMS4wPC9wPg0KCQk8cD5GaXJzdCB2ZXJzaW9uIHJlbGVhc2VkIG91dHNpZGUgc3ZuPC9wPg0KCQk8cD5GaXhlZCByZWxhdGl2ZSBpbWFnZS1zb3VyY2VzPC9wPg0KCQk8cD5Ob3cgc2hvd3MgdGhlIHN0eWxlc2hlZXQgb2YgdGhlIHBhZ2UgaWYgdGhlIHBsdWdpbiBTdHlsaXN0IGlzIGVuYWJsZWQgKGl0IGlzIGJ5IGRlZmF1bHQpPC9wPg0KCQk8L2xpPg0KCQk8bGk+DQoJCTxwPlZlcnNpb246IDAuMC4yPC9wPg0KCQk8cD5GaXhlZCBhIHByb2JsZW0gd2hpY2ggYWZmZWN0ZWQgdGhlIHRhYnMgb24gYWxsIGFkbWluLXBhZ2VzPC9wPg0KCQk8cD5GaXhlZCBzb21lIHBocDUtcmVsYXRlZCBwcm9ibGVtczwvcD4NCgkJPHA+VGhlIG1vZHVsZSBub3cgdHJpZXMgdG8gZmlndXJlIG91dCB5b3VyIGxhbmd1YWdlIHByZWZlcmVuY2UgYW5kIGFkanVzdCB0byB0aGF0PC9wPg0KCQk8L2xpPg0KCQk8bGk+DQoJCTxwPlZlcnNpb246IDAuMC4xPC9wPg0KCQk8cD5Jbml0aWFsIHRlc3QgcmVsZWFzZS48L3A+DQoJCTwvbGk+DQoJCTwvdWw+JzsKPz4=]]></data>
	</file>
	<file>
	  <filename>/lang/ext/da_DK.php</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[PD9waHAKJGxhbmdbJ3NldHRpbmdzJ10gPSAnSW5kc3RpbGxpbmdlcic7CiRsYW5nWydwbHVnaW5zJ10gPSAnVWR2aWRlbHNlcic7CiRsYW5nWydzZWxlY3Rza2luJ10gPSAnViZhZWxpZztsZyB1ZHNlZW5kZSc7CiRsYW5nWydzZWxlY3R3aWR0aCddID0gJ0JyZWRkZSBmb3IgaW5kdGFzdG5pbmdzZmVsdCc7CiRsYW5nWydzZWxlY3RoZWlnaHQnXSA9ICdIJm9zbGFzaDtqZGUgZm9yIGluZHRhc3RuaW5nc2ZlbHQnOwokbGFuZ1snYXV0byddID0gJ1MmYWVsaWc7dCBhdXRvbWF0aXNrLCBlbGxlciBzJmFlbGlnO3QgdGlsOic7CiRsYW5nWydzZWxlY3RzdHlsZXdpZHRoJ10gPSAnQnJlZGRlIGFmIHBhbmVsZXQgbWVkIFN0eWxpc3QgdWR2aWRlbHNlbic7CiRsYW5nWydleGFtcGxlJ10gPSAnRWtzZW1wZXQgcCZhcmluZzsgaW5kdGFzdG5pbmdzZmVsdCc7CiRsYW5nWydwaXhlbHMnXSA9ICdQaXhlbHMnOwokbGFuZ1snYm9keWNzcyddID0gJ0JvZHkgQ1NTJzsKJGxhbmdbJ2xpbmtlcmZsYXZvciddID0gJ0NNU01TTGlua2VyIHN0eWxlJzsKJGxhbmdbJ2hyZWZmbGF2b3InXSA9ICdHZW5lciZlYWN1dGU7ciBzdGFuZGFyZCBocmVmLXN0eWxlIGxpbmtzJzsKJGxhbmdbJ3NlbGZsaW5rZmxhdm9yJ10gPSAnR2VuZXImZWFjdXRlO3IgQ01TTVMtc2VsZmxpbmstc3R5bGUgbGlua3MnOwokbGFuZ1sndmFsaWRjc3MnXSA9ICdBZHZhcnNlbCEgRGV0dGUgc2thbCB2JmFlbGlnO3JlIGV0IGd5bGRpZ3QgQ1NTLXVkdHJ5ayc7CiRsYW5nWydvayddID0gJ09LJzsKJGxhbmdbJ3Rlc3RpbmdhcmVhJ10gPSAnRGV0dGUgZXIgZXQgZWtzZW1wZWwgcCZhcmluZzsgZXIgaW5kdGFzdG5pbmdzZmVsdC4gSW50ZXQgaW5kaG9sZCB2aWwgYmxpdmUgYmVyJm9zbGFzaDtydCBhZiBhdCBsZWdlIG1lZCBkZW5uZS4nOwokbGFuZ1sncG9zdGluc3RhbGwnXSA9ICdNb2R1bGV0IGJsZXYgaW5zdGFsbGVyZXQhIFNsJmFyaW5nOyAmIzAzOTtNb2RpZnkgWGluaGEtc2V0dGluZ3MmIzAzOTstdGlsbGFkZWxzZW4gdGlsIGZvciBkZSBncnVwcGVyIGRlciBza2FsIGhhdmUgbG92IHRpbCBhdCBpbmRzdGlsbGUgWGluaGEuJzsKJGxhbmdbJ3NldHRpbmdzc2F2ZWQnXSA9ICdJbmRzdGlsbGluZ2VyIGdlbXQnOwokbGFuZ1snbmV3cGx1Z2lucyddID0gJ0RlIHZhbGd0ZSBwbHVnaW5zIGVyIHNsJmFyaW5nO2V0IHRpbCc7CiRsYW5nWydub2FjY2VzcyddID0gJ0R1IHNrYWwgaGF2ZSAlcy10aWxsYWRlbHNlbiBmb3IgYXQga3VubmUgZiZhcmluZzsgYWRnYW5nIGhlcnRpbCEnOwokbGFuZ1snaGVscCddID0gJzxoMz5XaGF0IGRvZXMgdGhpcyBkbz88L2gzPg0KICAgIDxwPkVuYWJsZXMgPGI+WGluaGE8L2I+IHRvIGJlIHVzZWQgYXMgYSBXWVNJV1lHLjwvcD4NCiAgICA8aDM+SG93IGRvIEkgdXNlIGl0PzwvaDM+DQogICAgPHA+SW5zdGFsbCBpdCwgdGhlbiBnbyB0byBVc2VyIFByZWZlcmVuY2VzIGFuZCBTZXQgPGI+WGluaGE8L2I+IHRvIGJlIHlvdXIgd3lzaXd5ZyBvZiBjaG9pY2UuPC9wPiYjMDM5OzsNCiAgICA8cD5UbyBjdXN0b21pemUgaXQgdGhlIHBlcm1pc3Npb24gPGk+TW9kaWZ5IFhpbmhhLXNldHRpbmdzPC9pPiBtdXN0IGJlIHNldCBmb3IgeW91IGdyb3VwLjwvcD4nOwokbGFuZ1snY2hhbmdlbG9nJ10gPSAnCQk8dWw+DQoJCTxsaT4NCgkJPHA+VmVyc2lvbjogMC4xLjM8L3A+DQoJCTxwPlByZXBhcmVkIGl0IHRvIGJlIG9wdGlvbmFsIHdoZXRoZXIgdGhlIGNtc21zbGlua2VyIHNob3VsZCBnZW5lcmF0ZSBocmVmLXN0eWxlIG9yIHtjbXMtc2VsZmxpbmt9LXN0eWxlIGxpbmtzPC9wPg0KCQk8L2xpPg0KCQk8bGk+DQoJCTxwPlZlcnNpb246IDAuMS4yPC9wPg0KCQk8cD5BZGRlZCBwZXJtaXNzaW9uIHRvIGNoYW5nZSBzZXR0aW5nczwvcD4NCgkJPHA+QWRkZWQgYSBDTVMtbGlua2VyIG1vZHVsZSB0byBYaW5oYTwvcD4NCgkJPHA+QWRkZWQgdGhlIE11bHRpQ29uZmlndXJhdGlvbiBwbHVnaW4gdG8gWGluaGE8L3A+DQoJCTwvbGk+DQoJCTxsaT4NCgkJPHA+VmVyc2lvbjogMC4xLjE8L3A+DQoJCTxwPkZpeGVkIGF1dG9kZXRlY3Rpb24gb2YgU3dlZGlzaDwvcD4NCgkJPHA+Rml4ZWQgdGhlIHByb2JsZW0gd2l0aCBoYW5naW5nIGZvcm0tYnV0dG9ucyB3aGVuIGluIGZ1bGxzY3JlZW4gbW9kZTwvcD4NCgkJPHA+Tm8gdWdseSBoZWFkZXIgc3R1ZmYgaW5zZXJ0ZWQgaW50byBwYWdlcyBub3QgY29udGFpbmluZyBhICYjMDM5O3RleHRhcmVhJiMwMzk7IHRhZzwvcD4NCgkJPHA+Rml4ZWQgWGluaGEgbm90IHNob3dpbmcgd2hlbiBlZGl0aW5nIG5ld3MuLi48L3A+DQoJCTxwPkFkZGVkIHdpZHRoIG9mIGVkaXRvci1hcmVhIGFzIGFuIG9wdGlvbjwvcD4NCgkJPHA+QWRkZWQgYSBleGFtcGxlIHRleHQtYXJlYTwvcD4NCgkJPHA+QWRkZWQgd2lkdGggb2YgdGhlIFN0eWxpc3QgcGFuZWwgYXMgYW4gb3B0aW9uPC9wPg0KICAgIDxwPkZpeGVkIHNob3J0X29wZW5fdGFnczwvcD4NCiAgICA8cD48L3A+DQoJCTwvbGk+DQoJCTxsaT4NCgkJPHA+VmVyc2lvbjogMC4xLjA8L3A+DQoJCTxwPkZpcnN0IHZlcnNpb24gcmVsZWFzZWQgb3V0c2lkZSBzdm48L3A+DQoJCTxwPkZpeGVkIHJlbGF0aXZlIGltYWdlLXNvdXJjZXM8L3A+DQoJCTxwPk5vdyBzaG93cyB0aGUgc3R5bGVzaGVldCBvZiB0aGUgcGFnZSBpZiB0aGUgcGx1Z2luIFN0eWxpc3QgaXMgZW5hYmxlZCAoaXQgaXMgYnkgZGVmYXVsdCk8L3A+DQoJCTwvbGk+DQoJCTxsaT4NCgkJPHA+VmVyc2lvbjogMC4wLjI8L3A+DQoJCTxwPkZpeGVkIGEgcHJvYmxlbSB3aGljaCBhZmZlY3RlZCB0aGUgdGFicyBvbiBhbGwgYWRtaW4tcGFnZXM8L3A+DQoJCTxwPkZpeGVkIHNvbWUgcGhwNS1yZWxhdGVkIHByb2JsZW1zPC9wPg0KCQk8cD5UaGUgbW9kdWxlIG5vdyB0cmllcyB0byBmaWd1cmUgb3V0IHlvdXIgbGFuZ3VhZ2UgcHJlZmVyZW5jZSBhbmQgYWRqdXN0IHRvIHRoYXQ8L3A+DQoJCTwvbGk+DQoJCTxsaT4NCgkJPHA+VmVyc2lvbjogMC4wLjE8L3A+DQoJCTxwPkluaXRpYWwgdGVzdCByZWxlYXNlLjwvcD4NCgkJPC9saT4NCgkJPC91bD4nOwo/Pg==]]></data>
	</file>
	<file>
	  <filename>/lang/ext/de_DE.php</filename>
	  <isdir>0</isdir>